---
# tasks file for visualcode_extensions
- name: Terminal extension installation
  command: code --install-extension formulahendry.terminal
  tags:
  - default_extensions

- name: Auto Close Tag extension installation
  command: code --install-extension formulahendry.auto-close-tag
  tags:
  - default_extensions
  - frontend_extensions

- name: Ansible extension installation
  command: code --install-extension vscoss.vscode-ansible
  tags:
  - ansible_extensions

- name: CircleCI extension installation
  command: code --install-extension jvandyke.vscode-circleci
  tags:
  - infra_extensions
  - devops_extensions

- name: Color Picker extension installation
  command: code --install-extension anseki.vscode-color
  tags:
  - frontend_extensions