---
# tasks file for visualcode_extensions
- name: Terminal extension installation
  command: code --install-extension formulahendry.terminal
  tags:
  - default_extensions

- name: Auto Close Tag extension installation
  command: code --install-extension formulahendry.auto-close-tag
  tags:
  - default_extensions
  - frontend_extensions

- name: Ansible extension installation
  command: code --install-extension vscoss.vscode-ansible
  tags:
  - ansible_extensions

- name: CircleCI extension installation
  command: code --install-extension jvandyke.vscode-circleci
  tags:
  - infra_extensions
  - devops_extensions

- name: Color Picker extension installation
  command: code --install-extension anseki.vscode-color
  tags:
  - frontend_extensions

- name: Debugger for Java extension installation
  command: code --install-extension vscjava.vscode-java-debug
  tags:
  - developer_extensions
  - java_extensions

- name: Docker extension installation
  command: code --install-extension ms-azuretools.vscode-docker
  tags:
  - infra_extensions
  - devops_extensions

- name: EditorConfig extension installation
  command: code --install-extension editorconfig.editorconfig
  tags:
  - default_extensions

- name: Git Project Manager extension installation
  command: code --install-extension felipecaputo.git-project-manager
  tags:
  - default_extensions
  - developer_extensions

- name: Golang extension installation
  command: code --install-extension ms-vscode.go
  tags:
  - golang_extensions
  - developer_extensions

- name: GoCD extension installation
  command: code --install-extension inlustra.vscode-go-cd
  tags:
  - infra_extensions
  - devops_extensions

- name: Go Coverage extension installation
  command: code --install-extension defaltd.go-coverage-viewer
  tags:
  - golang_extensions
  - developer_extensions

- name: Go Critic extension installation
  command: code --install-extension neverik.go-critic
  tags:
  - golang_extensions
  - developer_extensions

- name: Go Test Explorer extension installation
  command: code --install-extension premparihar.gotestexplorer
  tags:
  - golang_extensions
  - developer_extensions

- name: Golang TDD extension installation
  command: code --install-extension joaoacdias.golang-tdd
  tags:
  - golang_extensions
  - developer_extensions