---

repos:
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        args:
          - --rules
          - ~MD013

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args:
          - --strict
        skip_list:
          - yaml[truthy]

default_stages:
  - commit
  - merge-commit
