---
# tasks file for tfenv_macos
  - name: Clone TFEnv - Terraform Environments
    git:
      repo: https://github.com/tfutils/tfenv.git
      dest: ${HOME}/.tfenv
  - name: List TFEnv binary files
    find:
      paths: ${HOME}/.tfenv/bin
    register: find

  - name: Create binaries symbolic link 
    file:
      src: "{{ item.path }}"
      dest: "/usr/local/bin/{{ item.path | basename }}"
      state: link
    with_items: "{{ find.files }}"