---
# tasks file for telegram_macos
  - name: Download Telegram Package
    get_url:
      url: https://updates.tdesktop.com/tmac/tsetup.3.3.0.dmg
      dest: /tmp/telegram.dmg

  - name: Telegram package uncompress
    become: yes
    command: hdiutil attach /tmp/telegram.dmg

  - name: Telegram package installation
    become: yes
    command: cp -r /Volumes/Telegram\ Desktop/Telegram.app /Applications

  - name: Telegram package umounting
    become: yes
    command: hdiutil detach /Volumes/Telegram\ Desktop

  - name: Remove installation package
    file:
      path: /tmp/telegram.dmg
      state: absent