---
- name: Download VisualCode on macOs
  get_url:
    url: https://go.microsoft.com/fwlink/?LinkID=620882
    dest: /tmp
    mode: 0755

- name: Uncompress VisualCode installation
  unarchive:
    src: /tmp/VSCode-darwin.zip
    dest: /tmp/

- name: Set VisualCode app into Application
  command: mv "/tmp/Visual Studio Code.app" /Applications/

- name: Remove installation package from machine
  file:
    path: /tmp/VSCode-darwin.zip
    state: absent
  
