---
- name: Download VisualCode on macOs
  get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal
    dest: ./VSCode-darwin.zip
    mode: 0755

- name: Uncompress VisualCode installation
  unarchive:
    src: ./VSCode-darwin.zip
    dest: ./

- name: Set VisualCode app into Application
  copy: remote_src=True src="./Visual Studio Code.app" dest=/Applications/

- name: Remove installation package from machine
  file:
    path: ./VSCode-darwin.zip
    state: absent
  
