---
# tasks file for spotify_macos
  - name: Download Spotify Package
    get_url:
      url: https://download.scdn.co/SpotifyInstaller.zip
      dest: /tmp/Spotify.zip

  - name: Uncompress installation package
    command: unzip /tmp/Spotify.zip -d /tmp/Spotify

  - name: move Spotify package installation to MacOs Applications
    become: yes
    command: cp -r "/tmp/Spotify/Install Spotify.app" /Applications

  - name: Spotify installation
    command: open -a "/tmp/Spotify/Install Spotify.app"

  - name: Remove installation package folder
    file:
      path: /tmp/Spotify
      state: absent

  - name: Remove installation package
    file:
      path: /tmp/Spotify.zip
      state: absent