---
# tasks file for azurecli_macos
- name: Azure CLI installation
  command: brew install azure-cli

- name: Gettting Azure CLI version installed
  command: az version
  register: az_version

- debug: msg="{{ az_version.stdout }}"
