---
# tasks file for virtualbox_macos
- name: Download VirtualBox Runtime Package
  get_url:
    url:
      https://download.virtualbox.org/virtualbox/7.0.18/VirtualBox-7.0.18-162988-OSX.dmg
    dest: ./VirtualBox.dmg

- name: VirtualBox package uncompress
  command: hdiutil attach ./VirtualBox.dmg

- name: VirtualBox package installation
  command: installer -pkg /Volumes/VirtualBox/VirtualBox.pkg -target /
  become: true

- name: VirtualBox package umounting
  command: hdiutil detach /Volumes/VirtualBox

- name: Remove installation package
  file:
    path: ./VirtualBox.dmg
    state: absent
