---
# tasks file for virtualbox_macos
- name: Download VirtualBox Runtime Package
  get_url:
    url: http://download.virtualbox.org/virtualbox/5.0.40/VirtualBox-5.0.40-115130-OSX.dmg
    dest: ./VirtualBox.dmg

- name: VirtualBox package uncompress
  command: hdiutil attach ./VirtualBox.dmg

- name: VirtualBox package installation
  command: installer -pkg /Volumes/VirtualBox/VirtualBox.pkg -target /
  become: yes

- name: VirtualBox package umounting
  command: hdiutil detach /Volumes/VirtualBox

- name: Remove installation package
  file:
    path: ./VirtualBox.dmg
    state: absent